### ISSUE TITLE
Vert.x buffer overflow when sending AMQP messages

### ISSUE THREAD

**Issue by belks** [smallrye/smallrye-reactive-messaging#1541]
Hi,

we encountered some strange issues with Vert.x when using smallrye-reactive-messaging and ActiveMQ - see exception below.
I hope you can help or point us in the right direction if we are doing something completely wrong.

`Uncaught exception received by Vert.x - Exception: newPosition > limit: (65536 > 32768) - java.lang.IllegalArgumentException: newPosition > limit: (65536 > 32768)
	at java.base/java.nio.Buffer.createPositionException(Buffer.java:341)
	at java.base/java.nio.Buffer.position(Buffer.java:316)
	at java.base/java.nio.ByteBuffer.position(ByteBuffer.java:1516)
	at java.base/java.nio.ByteBuffer.position(ByteBuffer.java:267)
	at org.apache.qpid.proton.engine.impl.FrameWriterBuffer.transferTo(FrameWriterBuffer.java:215)
	at org.apache.qpid.proton.engine.impl.FrameWriter.readBytes(FrameWriter.java:73)
	at org.apache.qpid.proton.engine.impl.TransportImpl.writeInto(TransportImpl.java:376)
	at org.apache.qpid.proton.engine.impl.TransportOutputAdaptor.pending(TransportOutputAdaptor.java:59)
	at org.apache.qpid.proton.engine.impl.SaslImpl$SwitchingSaslTransportWrapper.pending(SaslImpl.java:842)
	at org.apache.qpid.proton.engine.impl.HandshakeSniffingTransportWrapper.pending(HandshakeSniffingTransportWrapper.java:138)
	at org.apache.qpid.proton.engine.impl.TransportImpl.pending(TransportImpl.java:1591)
	at org.apache.qpid.proton.engine.impl.TransportImpl.getOutputBuffer(TransportImpl.java:1540)
	at io.vertx.proton.impl.ProtonTransport.flush(ProtonTransport.java:273)
	at io.vertx.proton.impl.ProtonTransport$IdleTimeoutCheck.handle(ProtonTransport.java:305)
	at io.vertx.proton.impl.ProtonTransport$IdleTimeoutCheck.handle(ProtonTransport.java:294)
	at io.vertx.core.impl.VertxImpl$InternalTimerHandler.handle(VertxImpl.java:952)
	at io.vertx.core.impl.VertxImpl$InternalTimerHandler.handle(VertxImpl.java:919)
	at io.vertx.core.impl.EventLoopContext.emit(EventLoopContext.java:50)
	at io.vertx.core.impl.ContextImpl.emit(ContextImpl.java:274)
	at io.vertx.core.impl.EventLoopContext.emit(EventLoopContext.java:22)
	at io.vertx.core.impl.AbstractContext.emit(AbstractContext.java:53)
	at io.vertx.core.impl.EventLoopContext.emit(EventLoopContext.java:22)
	at io.vertx.core.impl.VertxImpl$InternalTimerHandler.run(VertxImpl.java:942)
	at io.netty.util.concurrent.PromiseTask.runTask(PromiseTask.java:98)
	at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:170)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:833)`

About our system. We are in the process of splitting up a monolithic component into smaller independent pieces. For that purpose we added:
- In-memory ActiveMQ Arthemis
- 1 emitter sending to queue A
- 1 consumer consuming queue A and sending data to queues B and C
- 1 consumer consuming queue B and 1 consuming queue C

All data is sent as plain byte arrays in the messages. 

The in-memory ActiveMQ, the emitter and all consumers are running in the same JVM (zulu17.28.13-ca-jdk17.0.0-win_x64 locally and Zulu17.28+14-SA build 17+35-LTS on Openshift) because we are still a transitioning phase as mentioned above.

Our application is running on Openshift, but the issue also happens locally on our Windows machines. However, it does not happen deterministically. Sometimes we encounter the issue immediately when processing data, sometimes only after a few hours. 

After the Vert.x exception the application continues to run, but the messages presented to the consumers by smallrye-reactive-messaging then contain incomplete byte arrays, which then causes our application to throw exceptions.

Versions:
artemis-server 2.17.0
artemis-amqp-protocol 2.17.0
quarkus-universe-bom 2.4.0.Final
quarkus-smallrye-reactive-messaging-amqp 2.4.0.Final

Our config:
```
mp:
  messaging:
    outgoing:
      queue-A-out:
        connector: smallrye-amqp
        address: A-queue
        durable: true
        tracing-enabled: false
      queue-B-out:
        connector: smallrye-amqp
        address: B-queue
        durable: true
        tracing-enabled: false
      queue-C-out: 
        connector: smallrye-amqp
        address: C-queue
        durable: true
        tracing-enabled: false
    incoming:
      queue-A-in: 
        connector: smallrye-amqp
        address: A-queue
        durable: false
        tracing-enabled: false
      queue-B-in:
        connector: smallrye-amqp
        address: B-queue
        durable: false
        tracing-enabled: false
      queue-C-in:
        connector: smallrye-amqp
        address: C-queue
        durable: false
        tracing-enabled: false
```

ActiveMQ acceptor URL:
```
tcp://127.0.0.1:5672?jms.copyMessageOnSend=false&jms.prefetchPolicy.all=1000&amqpMinLargeMessageSize=1048576&jms.useAsyncSend=true&jms.optimizeAcknowledge=true&jms.redeliveryPolicy.maximumRedeliveries=-1&compressLargeMessages=false&protocols=AMQP&jms.useCompression=false
```

Our code: 

Emitter sending to queue A:
```private final Emitter<byte[]> emitterQueueA;

    @Inject
    public Creator(@Channel("queue-A-out") @OnOverflow(value = NONE) Emitter<byte[]> emitter) {
        this.emitter = emitter;
    }

   public void produce(OurMessage message) {
        // used by multiple theads at the same time. But should be fine. Emitter.send() is synchronized
        emitter.send(message.toBytes()).toCompletableFuture().join();
    }
```

Consumer consuming queue A and sending data to queues B and C:
```
    private final Emitter<byte[]> emitterQueueB;
    private final Emitter<byte[]> emitterQueueC;

    @Inject
    public Transformer(
            @Channel("queue-B-out") @OnOverflow(value = NONE) Emitter<byte[]> emitterQueueB,
            @Channel("queue-C-out") @OnOverflow(value = NONE) Emitter<byte[]> emitterQueueC) {
        // ... usual constructor stuff
    }

    @Incoming("queue-A-in")
    @Blocking(value = "WorkerPool-A", ordered = false)
    public CompletionStage<Void> transform(Message<byte[]> message) {
           // process message
           byte[] messageData = .... // build new message
           CompletionStage<Void> firstMsg = emitterQueueB.send(messageData);
           CompletionStage<Void> secondMsg = emitterQueueC.send(messageData);
           firstMsg.thenCombine(secondMsg, (void1, void2) -> null).toCompletableFuture().join();
           return message.ack();
    }
```

Consumer consuming queue B:
```
    @Incoming("queue-B-in")
    @Blocking(value = "WorkerPool-B", ordered = false)
    public CompletionStage<Void> consume(Message<byte[]> message) {
         // process message
         return message.ack();
    }
```

Consumer consuming queue C:
```
    @Incoming("queue-C-in")
    @Blocking(value = "WorkerPool-C", ordered = false)
    public CompletionStage<Void> consume(Message<byte[]> message) {
        // process message
         return message.ack();
    }
```
