### ISSUE TITLE
Unknown connector 'smallrye-kafka' in Quarkus 2.6.3

### ISSUE THREAD

**Issue by LazaroR94** [smallrye/smallrye-reactive-messaging#1582]
I recently upgraded to the newest Quarkus version and seem to be having some issues with the configuration of Smallrye's reactive messaging. Prior to 2.6.3, the connector has always been smallrye-kafka, but it seems I am having a strange error now when I run my application in that it cannot identify that as a known Kafka connector?

Error:

```
[error]: Build step io.quarkus.arc.deployment.ArcProcessor#generateResources threw an exception: javax.enterprise.inject.spi.DeploymentException: Found 2 deployment problems: 
[1] The channel 'kafka-data' is configured with an unknown connector (smallrye-kafka)
[2] The channel 'dlq-data' is configured with an unknown connector (smallrye-kafka)
```

This is my configuration (real values omitted for demonstration purposes):

```
mp:
  messaging:
    incoming:
      dlq-data:
        health-topic-verification-enabled: true
        connector: smallrye-kafka
        topic: ${kafka.topic.dlq}
        failure-strategy: ignore
        broadcast: true
        value:
          deserializer: myOwnCustomDeserializer
        auto:
          offset:
            reset: earliest
        enable:
          auto:
            commit: false
        group:
          id: someGroupId
      kafka-data:
        health-topic-verification-enabled: true
        connector: smallrye-kafka
        topic: ${kafka.topic.fulfillment}
        failure-strategy: dead-letter-queue
        dead-letter-queue:
          topic: ${kafka.topic.dlq}
          value:
            serializer: io.quarkus.kafka.client.serialization.ObjectMapperSerializer
        broadcast: true
        value:
          deserializer: myOwnCustomDeserializer
        auto:
          offset:
            reset: earliest
        enable:
          auto:
            commit: false
        group:
          id: someGroupId
```

The only thing I can gather from the official documentation is that some reactive messaging packages were split but there is no mention about this connector changing (seeing that I'm sure it did not change).

**Comment by ozangunalp** [comment]
It's very tricky to reproduce this. I don't have the issue with 2.6.3 with a simple project.
If you can post the output of `mvn dependency:tree` I can look further. 

I don't think it is related but you can try disabling the auto connector attachment feature to see if it's causing the issue : 
```yml
quarkus:
  reactive-messaging:
    auto-connector-attachment: false
```
