### ISSUE TITLE
Erroneous warning about unrecognised config `merge` for producer using smallrye-reactive-messaging-kafka

### ISSUE THREAD

**Issue by josephearl** [smallrye/smallrye-reactive-messaging#1673]
We are using `smallrye-reactive-messaging-kafka` and have multiple producers sending messages to a single Kafka topic

To do this we have configured the topic with the `merge: true`:

```
mp:
  messaging:
    outgoing:
      my-topic:
        topic: foo.bar
        value:
          serializer: io.quarkus.kafka.client.serialization.ObjectMapperSerializer
        connector: smallrye-kafka
        merge: true
```

On startup of the application there is a warning about an unrecognised configuration:

```
WARN  [org.apa.kaf.cli.pro.ProducerConfig] (Quarkus Main Thread) The configuration 'merge' was supplied but isn't a known config.
```

However removing `merge: true` from the config results in an exception on startup:

```
TooManyUpstreamCandidatesException: 'mp.messaging.outgoing.my-topic.merge=true' + to allow multiple upstreams.
```

This warning seems erroneous.

It looks like the merge property should be removed before passing the config to the Kafka client itself.
