### ISSUE TITLE
Document usages of _managed_ Kafka

### ISSUE THREAD

**Issue by cescoffier** [smallrye/smallrye-reactive-messaging#1695]
This epic is about adding detailed documentation about:

- [ ] Amazon MSK
- [ ]  Azure Service Hub
- [ ]  Red Hat OpenShift Streams with Apache Kafka
- [ ]  Confluent Cloud

The document should explain how to configure the Kafka connector to work with these providers.

**Comment by mazenkhalil** [comment]
Does this epic includes the support of [azure-schema-registry-for-kafka](https://github.com/Azure/azure-schema-registry-for-kafka)?

**Comment by cescoffier** [comment]
Yes.

**Comment by cescoffier** [comment]
Followed up by https://github.com/quarkusio/quarkus-upstream-roadmap/issues/14.

```yaml
organization: QuarkusIO
repository: quarkus-upstream-roadmap
issue: 14
url: https://github.com/quarkusio/quarkus-upstream-roadmap/issues/14
```
