### ISSUE TITLE
False warning: "These configurations '[topic.name]' were supplied but are not used yet"

### ISSUE THREAD

**Issue by Hubbitus** [smallrye/smallrye-reactive-messaging#2358]
That was fixed previously in https://github.com/smallrye/smallrye-reactive-messaging/issues/361.

But it looks like key `topic` changed to `topic.name` and problem re-appeared.

**Comment by ozangunalp** [comment]
I am missing some context. Which key changed to `topic.name`? Certainly there wasn't a change in the Kafka connector side.

**Comment by Hubbitus** [comment]
By https://github.com/smallrye/smallrye-reactive-messaging/issues/361 `topic` item was excluded from warning as unknown configuration element, but now same warning produced for the `topic.name` element.

**Comment by ozangunalp** [comment]
That's normal `topic.name` is not a config attribute read by the Kafka connector, hence it is passed to the underlying Kafka client, which doesn't recognize it and log this. I don't see any issue here.

**Comment by Hubbitus** [comment]
@ozangunalp, and why then `smallrye-reactive-messaging` passing it to the kafka??

**Comment by Hubbitus** [comment]
Receive but warns that is incorrect. Is not?

**Comment by cescoffier** [comment]
It's the behavior of the Apache Kafka client. It warns for every unknown property, but at the same time, these properties may be used by classes not known by the client (like serde).

**Comment by Hubbitus** [comment]
Ok. Why you was fix that issue in the past (https://github.com/smallrye/smallrye-reactive-messaging/issues/361) for the `topic` configuration name, but refuses now for the `topic.name` after renaming on your side??

**Comment by ozangunalp** [comment]
There hasn't been any renaming. `topic` is still the channel attribute for configuring Kafka topics. Please see https://smallrye.io/smallrye-reactive-messaging/latest/kafka/receiving-kafka-records/#configuration-reference and https://smallrye.io/smallrye-reactive-messaging/latest/kafka/writing-kafka-records/#configuration-reference for configuration references

**Comment by Hubbitus** [comment]
@ozangunalp, but `topic.name` is not?

**Comment by cescoffier** [comment]
Please raise this issue to the Apache Kafka project - we cannot do much here.

**Comment by Hubbitus** [comment]
Am I wrong, you are dealing with other names in https://github.com/smallrye/smallrye-reactive-messaging/commit/5b68010825afb825df04ea6712a7c7252a240ebe?

**Comment by cescoffier** [comment]
We are only dealing with connector attributes we know (as we defined them). Topic.name is not part of that group.

**Comment by Hubbitus** [comment]
@cescoffier, I've use next configuration of messaging:
```yaml
mp:
  messaging:
    # Configuring the outgoing channel (writing to Kafka)
    outgoing:
      tracking-out:
        connector: smallrye-kafka
        topic: ${KAFKA_TOPIC_NAME:dev.tmp.tracking}
        key:
          serializer: org.apache.kafka.common.serialization.StringSerializer
        value:
          serializer: org.apache.kafka.common.serialization.StringSerializer
        merge: true

kafka:
  bootstrap:
    servers: 'kafka:19091,kafka:19092,kafka:19093'
  security:
    protocol: SSL
  ssl:
    truststore:
      location: ${SSL_TRUSTSORE_LOCATION:/some/path/truststore.jks}
      # Passwords *must* be set outside for the safety
    keystore:
      location: ${SSL_KEYSTORE_LOCATION:/some/path/keystore.jks}
      # password: ${KAFKA_SSL_KEYSTORE_PASSWORD}
```

All works fine, but constantly see warning:
```
These configurations '[topic.name]' were supplied but are not used yet
```
That spams Sentry with errors and my current workaround solution is use @LoggingFilter to filter out such messages.
