### ISSUE TITLE
Kafka DLQ config doesn't work will concurrency enabled topics

### ISSUE THREAD

**Issue by ozangunalp** [smallrye/smallrye-reactive-messaging#2766]
When concurrency is enabled, the DLQ producer config doesn't get the correct properties from the main channel config.

Example config : 
```
mp:
  messaging:
    incoming:
      material-batch-reader:
        connector: smallrye-kafka
        concurrency: 5
        health-topic-verification-enabled: true
        throttled:
          unprocessed-record-max-age:
            ms: 100000
        bootstrap:
          servers: ${my.bootstrap.url}
        sasl:
          jaas:
            config: 'org.apache.kafka.common.security.plain.PlainLoginModule required username="${myusername}" password="${mypassword}";'
        group:
          id: ${myconsumergroup}
        topic: com.mydomain.mytopicname
        key:
          deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
        value:
          deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
        fail-on-deserialization-failure: false
        failure-strategy: dead-letter-queue
        dead-letter-queue:
          topic: com.mydomain.dlq.mytopicname
          key:
            serializer: org.apache.kafka.common.serialization.ByteArraySerializer
          value:
            serializer: org.apache.kafka.common.serialization.ByteArraySerializer
```

Reported by : https://quarkusio.zulipchat.com/#narrow/stream/187030-users/topic/smallrye-reactive-messaging-kafka.3A.20DLQ.20.2B.20concurrency/near/472725895
