### ISSUE TITLE
MQTT connector configuration - global configuration of MQTT connector

### ISSUE THREAD

**Issue by ozeil** [smallrye/smallrye-reactive-messaging#2917]
We have a use case in one of our quarkus applications utilizing smallrye reactive messaging where we have a lot of topics we listen to. Now, to avoid having to configure each attribute for every channel/topic we would like to be able to configure the connector globally, e.g. like this (uses a yaml config here):
```
mp:
  messaging:
    # Global connector configuration
    connector:
      smallrye-mqtt:
        host: hostname
        port: 1883
        username: user
        password: pw
        client-id: clientId
        max-message-size: 2147483
        qos: 1
        failure-strategy: ignore
    incoming:
      # MQTT channel configs
      firstTopic:
        connector: smallrye-mqtt
        topic: topic/first
      secondTopic:
        connector: smallrye-mqtt
        topic: topic/second
```
Unless the channel configuration overwrites what was globally configured the values from the global configuration should be used. This does not seem to be supported currently.

Would it be feasible to support something like this?
Thank you!
