### ISSUE TITLE
Quarkus application properties for consumer are somehow overridden

### ISSUE THREAD

**Issue by DaanDR** [smallrye/smallrye-reactive-messaging#2974]
Hi!

I'm trying to configure my consumer to consume msgs in batches, and want to tweak the fetch.min.bytes and fetch.max.wait.ms setting to make sure my consumer does not consume messages as soon as they're available. (another team wants to receive them in batches)

I'm trying to do this using the following configuration [as found here](https://smallrye.io/smallrye-reactive-messaging/smallrye-reactive-messaging/3.3/kafka/kafka.html#_configuration_reference):

```
mp:
  messaging:
    incoming:
      words-in:
        batch: true
        fetch.min.bytes: 2
        connector: smallrye-kafka
        topic: ${topic_words:words}
        value:
          deserializer: org.apache.kafka.common.serialization.StringDeserializer
```

I've put my "org.apache.kafka.clients.consumer" logging to debug, and this is the logging I see for this consumer (left out most of the unimportant parts) :

2025-03-13 10:58:49,780 INFO  [org.apa.kaf.cli.con.ConsumerConfig] (smallrye-kafka-consumer-thread-0) ConsumerConfig values: 
        allow.auto.create.topics = true
        auto.commit.interval.ms = 5000
        auto.include.jmx.reporter = true
        auto.offset.reset = latest
        bootstrap.servers = [OUTSIDE://localhost:37283]
        check.crcs = true
        client.dns.lookup = use_all_dns_ips
        client.id = kafka-consumer-words-in
        client.rack = 
        connections.max.idle.ms = 540000
        default.api.timeout.ms = 60000
        enable.auto.commit = false
        enable.metrics.push = true
        exclude.internal.topics = true
        fetch.max.bytes = 52428800
        fetch.max.wait.ms = 500
        **fetch.min.bytes = 1** ⬅️
        group.id = smallrye-consumer-config-demo
        group.instance.id = null
        group.protocol = classic
        group.remote.assignor = null
        heartbeat.interval.ms = 3000
        interceptor.classes = []
        internal.leave.group.on.close = true
        internal.throw.on.fetch.stable.offset.unsupported = false
        isolation.level = read_uncommitted
        key.deserializer = class io.smallrye.reactive.messaging.kafka.fault.DeserializerWrapper
        max.partition.fetch.bytes = 1048576
        max.poll.interval.ms = 300000
        max.poll.records = 500
        metadata.max.age.ms = 300000
        metadata.recovery.strategy = none
        metric.reporters = []
        metrics.num.samples = 2

So it somehow seems to still be the default "1" value. 

Now when I add my IntelliJ run config with a "add Arguments" option and I add the following:

`-Dmp.messaging.incoming.words-in.fetch.min.bytes=2`

the logs show :

fetch.min.bytes = 2 ⬅️

Questions:
	•	Is this behavior a bug in SmallRye Reactive Messaging, or is there something missing in my YAML configuration?
	•	Are there any additional steps or known workarounds to ensure that the YAML file’s settings are applied as expected without relying on command-line overrides?

I included a simple demo app

[smallrye-consumer-config-demo.zip](https://github.com/user-attachments/files/19226878/smallrye-consumer-config-demo.zip)

**Comment by cescoffier** [comment]
Did you try with "fetch.min.bytes" ?

**Comment by DaanDR** [comment]
hmm. yes, like this right? (as shown above)

```
mp:
  messaging:
    incoming:
      words-in:
        batch: true
        **fetch.min.bytes: 2**
        connector: smallrye-kafka
        topic: ${topic_words:words}
        value:
          deserializer: org.apache.kafka.common.serialization.StringDeserializer
```

**Comment by DaanDR** [comment]
Tried the following but still shows default value "1"

```
mp:
  messaging:
    incoming:
      words-in:
        batch: true
        "fetch.min.bytes": 2
        connector: smallrye-kafka
        topic: ${topic_words:words}
        value:
          deserializer: org.apache.kafka.common.serialization.StringDeserializer
```

**Comment by DaanDR** [comment]
Okay this does seem to work:

```
mp:
  messaging:
    incoming:
      words-in:
        batch: true
        fetch:
          min:
            bytes: 2
        connector: smallrye-kafka
        topic: ${topic_words:words}
        value:
          deserializer: org.apache.kafka.common.serialization.StringDeserializer
```
