### ISSUE TITLE
Reprocessing of incoming nacked messages due to connection loss (kafka)

### ISSUE THREAD

**Issue by martindebatin** [smallrye/smallrye-reactive-messaging#3036]
## Question
Does smallrye-reactive-messaging support the reprocessing / reconsumption of messages that were nacked due to connection loss? If so, any recommendation how to achieve this?

## Context
In our current use case, we need to be able to consume messages from a Kafka topic, process them and send them using MQ. So far we have used the smallrye-kafka connector for Kafka and a custom extension for IBMMQ based on jakarta.jms for the outgoing channel. 

Our current solution for consuming, processing and forwarding messages is as follows: 

```
@Slf4j
@ApplicationScoped
public class Processor {

    private final ProcessorHelper processorHelper;

    public Processor(ProcessorHelper processorHelper) {
        this.processorHelper = processorHelper;
    }

    @Incoming("in") // kafka
    @Outgoing("out") // mq
    public Multi<String> processVpdMessage(String message) {
        return processorHelper.transformMessage(message) // maps it to a DTO, parses some fields to List<String> and returns a Multi<String>
                .onFailure()
                .invoke(this::logErrorMessage)
                .onFailure()
                .recoverWithCompletion(); // ensure the stream is not failed
    }

    private void logErrorMessage(Throwable cause) {
        log.error("Failed to process data. Not sending any messages to mq");
        if (cause instanceof BaseException) {
            ErrorCodeLogger.log(((BaseException) cause));
        } else if (cause instanceof ConstraintViolationException) {
            ErrorCodeLogger.log((ConstraintViolationException) cause);
        } else {
            ErrorCodeLogger.log(ErrorCode.UNEXPECTED_ERROR, cause);
        }
    }
}
```

During operation, we have now noticed that there are occasional disconnections on the side of MQ. In this case, messages are nacked. If the connection is re-established, no more messages are consumed. 

When switching to ignore as a failure strategy, new messages are consumed again. However, messages that could not be delivered during the connection failure are not sent again (since they get committed). So this is no valid option for us

We also tried different pre, post and manual acknowledgement strategies, but with  no success.

Current relevant configuration in application.yaml:

```
kafka:
  bootstrap:
    servers: localhost:29092
mp:
  messaging:
    incoming:
      in:
        topic: x-to-y
        connector: smallrye-kafka
        failure-strategy: ignore
        throttled:
          unprocessed-record-max-age:
            ms: 0

    out:
      vpdout:
        queue:
          name: P_QUEUE
        connector: quarkus-ibm
``` 

## Expected behavior
Messages that could not be sent due to connection loss, are consumed, processed and sent to the outgoing channel when connection is re-established. 

##  Current Environment
Quarkus: 3.9.3
smallrye-reactive-messaging: 4.19.0
Java: 17
