### ISSUE TITLE
Configuration of SQS outgoing channel without queue name

### ISSUE THREAD

**Issue by lschmierer** [smallrye/smallrye-reactive-messaging#3048]
Hi, I am using `SqsOutboundMetadata.builder().queueUrl(sqsQueueUrl)` to define the target queue based on the data at runtime.
Therefor I do not want to set a queue name in the outgoing channel configuration.

Because the queue name defaults to the channel name, I receive error `SRMSG19400: Failed to retrieve AWS Sqs queue url` (this queue does not exist).

However, there is a workaround by defining a "fake" url:
```yml
mp:
  messaging:
    outgoing:
      my-channel:
        connector: smallrye-rabbitmq
        queue:
          url: dummy/url
```

I am not quite sure how this would ideally look like, because the default behaviour seems sensible.
- maybe the lookup from queue name to queue url could be deferred until the first message is sent or
- add a config property to explicitly set the queue name and queue url to null?
