### ISSUE TITLE
Introduce failure management bean

### ISSUE THREAD

**Issue by cescoffier** [smallrye/smallrye-reactive-messaging#438]
The idea is to catch the processing failure of the following method shapes:

*  `X process(Y)` and  `Message<X> process(Message<Y>)`
* `CompletionStage<X> process(Y)` and `CompletionStage<Messasge<X>> process(Message<Y>)`

When a failure happens (synchronously or asynchronously), a `FailureHandler` bean is called with the failing message:

```
public interface FailureHandler {
       // return true or failse whether the stream consumption must continue
       boolean handleFailure(Message<X>, Throwable failure);
}
```

Only a 0..1 instance of this handler is allowed. If none, the failure is not handled and the processing stopped.

The FailureHandler implementation is provided by the user.

_Implementation details_:

The mediator method invocation must be wrapped into a "flatMap" to avoid canceling the upstream subscription.

**Comment by cescoffier** [comment]
With #573, nack has been added, already making a first step toward the new fault-tolerance model.

**Comment by cescoffier** [comment]
Followed up by https://github.com/quarkusio/quarkus/issues/24720.

```yaml
organization: GHUser@49974bee[bio=Quarkus: Supersonic Subatomic Java,blog=https://quarkus.io,company=<null>,email=<null>,followers=0,following=0,hireable=false,location=The clouds,login=quarkusio,name=QuarkusIO,type=Organization,createdAt=2019-02-14T16:18:52Z,id=47638783,nodeId=MDEyOk9yZ2FuaXphdGlvbjQ3NjM4Nzgz,updatedAt=2020-04-08T04:51:14Z,url=https://api.github.com/users/quarkusio]
repository: quarkus
issue: 24720
url: https://github.com/quarkusio/quarkus/issues/24720
```
