### ISSUE TITLE
MQTT - Add metadata support

### ISSUE THREAD

**Issue by cescoffier** [smallrye/smallrye-reactive-messaging#466]
The MQTT connector should provide inbound and outbound metadata classes instead of a `MqttMessage`

**Comment by cescoffier** [comment]
Followed up by https://github.com/quarkusio/quarkus/issues/24719.

```yaml
organization: GHUser@49974bee[bio=Quarkus: Supersonic Subatomic Java,blog=https://quarkus.io,company=<null>,email=<null>,followers=0,following=0,hireable=false,location=The clouds,login=quarkusio,name=QuarkusIO,type=Organization,createdAt=2019-02-14T16:18:52Z,id=47638783,nodeId=MDEyOk9yZ2FuaXphdGlvbjQ3NjM4Nzgz,updatedAt=2020-04-08T04:51:14Z,url=https://api.github.com/users/quarkusio]
repository: quarkus
issue: 24719
url: https://github.com/quarkusio/quarkus/issues/24719
```
