### ISSUE TITLE
Allow metadata injection for method receiving payload

### ISSUE THREAD

**Issue by cescoffier** [smallrye/smallrye-reactive-messaging#593]
For method receiving payload (list below), we should support the injection of message metadata:

```java
@Incoming("x")
public void consume(T payload, KafkaIncomingMetadata meta1) {
  // ...
}
```

Note that a message can be multiple metadata objects, so multiple parameters can be injected:

```java
@Incoming("x")
public void consume(T payload, KafkaIncomingMetadata meta1, TracingMetadata tracing) {
  // ...
}
```

Also, because metadata can be missing, we should add support for `Optional`:

```java
@Incoming("x")
public void consume(T payload, Optional<KafkaIncomingMetadata> meta1) {
  // ...
}
```

This would also mean that if `Optional` is not used, failure should be propagated in the case of missing metadata.

Signatures that should support this metadata injection are:

```
@Incoming("x") void method(P payload);
@Incoming("x") CompletionStage<Void> method(P payload);
@Incoming("x") Uni<Void> method(P payload);

@Outgoing("x") @Incoming("y") Publisher<O> method(P payload);
@Outgoing("x") @Incoming("y") Multi<O> method(P payload);
@Outgoing("x") @Incoming("y") PublisherBuilder<O> method(P payload);

@Outgoing("x") @Incoming("y") O method(P payload);
@Outgoing("x") @Incoming("y") CompletionStage<O> method(P payload);
@Outgoing("x") @Incoming("y") Uni<O> method(P payload);
```

**Comment by cescoffier** [comment]
Related to #588 .

**Comment by cescoffier** [comment]
Followed up by https://github.com/quarkusio/quarkus/issues/24717.

```yaml
organization: GHUser@49974bee[bio=Quarkus: Supersonic Subatomic Java,blog=https://quarkus.io,company=<null>,email=<null>,followers=0,following=0,hireable=false,location=The clouds,login=quarkusio,name=QuarkusIO,type=Organization,createdAt=2019-02-14T16:18:52Z,id=47638783,nodeId=MDEyOk9yZ2FuaXphdGlvbjQ3NjM4Nzgz,updatedAt=2020-04-08T04:51:14Z,url=https://api.github.com/users/quarkusio]
repository: quarkus
issue: 24717
url: https://github.com/quarkusio/quarkus/issues/24717
```
