### ISSUE TITLE
Feature Request: Customizing the underlying MQTT client 

### ISSUE THREAD

**Issue by Tockra** [smallrye/smallrye-reactive-messaging#693]
Hi,

a similar feature for the mqtt like: https://smallrye.io/smallrye-reactive-messaging/smallrye-reactive-messaging/2.2/amqp/amqp.html#amqp-customization would be very helpful.

At the moment I need to convert a ca.crt to a java key store to use it for the mqtt connection.
But it would be nice to have the option to use it without converting it.

T

**Comment by cescoffier** [comment]
Hello,

Can you open an issue in
https://github.com/smallrye/smallrye-reactive-messaging?
I might be something we want to generalize for all connectors using Vert.x
clients underneath.

Clement

**Comment by cescoffier** [comment]
Damned! Just realize it was already an issue...

**Comment by cescoffier** [comment]
Followed up by https://github.com/quarkusio/quarkus/issues/24718.

```yaml
organization: GHUser@49974bee[bio=Quarkus: Supersonic Subatomic Java,blog=https://quarkus.io,company=<null>,email=<null>,followers=0,following=0,hireable=false,location=The clouds,login=quarkusio,name=QuarkusIO,type=Organization,createdAt=2019-02-14T16:18:52Z,id=47638783,nodeId=MDEyOk9yZ2FuaXphdGlvbjQ3NjM4Nzgz,updatedAt=2020-04-08T04:51:14Z,url=https://api.github.com/users/quarkusio]
repository: quarkus
issue: 24718
url: https://github.com/quarkusio/quarkus/issues/24718
```
